### ISSUE TITLE
sql 访问失败

### ISSUE THREAD

**Issue by Flowergloden** [david082321/BiliRoaming-PHP-Server#49]
当启用缓存时会因无法访问数据库而解析失败

以下是由 nginx 托管的报错信息
```
2024/04/20 18:58:46 [error] 105474#105474: *2240 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function query() on string in /opt/BiliRoaming-PHP-Server/utils/functio
ns_cache.php:67
Stack trace:
#0 /opt/BiliRoaming-PHP-Server/utils/auth.php(8): get_userinfo_fromsql()
#1 /opt/BiliRoaming-PHP-Server/intl/gateway/v2/ogv/playurl/index.php(21): include('/opt/BiliRoamin...')
#2 {main}
```

**Comment by M1saka10010** [comment]
数据库配置有没有问题？

**Comment by Flowergloden** [comment]
经过验证数据库的权限并没有问题，所有的表都正常创建，但是唯独 “keys” 表无法访问，疑似 shadow 了关键字，不知道是不是恰好撞上了 MariaDB 与 MySql 的微小差别之一

以下是错误信息
![image](https://github.com/david082321/BiliRoaming-PHP-Server/assets/45900971/35a12baa-1b63-438f-b40a-046480143248)


> 数据库配置有没有问题？

**Comment by M1saka10010** [comment]
> 经过验证数据库的权限并没有问题，所有的表都正常创建，但是唯独 “keys” 表无法访问，疑似 shadow 了关键字，不知道是不是恰好撞上了 MariaDB 与 MySql 的微小差别之一
> 
> 以下是错误信息 ![image](https://private-user-images.githubusercontent.com/45900971/324220058-35a12baa-1b63-438f-b40a-046480143248.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NzAxMDIsIm5iZiI6MTcxMzY2OTgwMiwicGF0aCI6Ii80NTkwMDk3MS8zMjQyMjAwNTgtMzVhMTJiYWEtMWI2My00MzhmLWI0MGEtMDQ2NDgwMTQzMjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDAzMjMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhZGIyZGY5NTcwZTk0NGMwZTllZTI1MjM2NzJmZWM4MmNmOGJkNjc0MGNmNjQ2OTU3ZWQ3YWQ3YWM5NDIwZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nWJZl1j_z7lIybrGFtc76gLNRga1GvCX5LRATMuCSx4)
> 
> > 数据库配置有没有问题？

那应该就是这个问题了，尝试一下手动创建？我看sql基本都没用到很复杂的特性，理论上是兼容的诶
